version: '3.8'

services:
  web:
    build: .
    container_name: music_hub_web
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
